### ISSUE TITLE
Test Failures on GTX2080Ti

### ISSUE THREAD

**Issue by wenxinnnnn** [filecoin-project/bellman#236]
```
# RUSTFLAGS="-C target-cpu=native" cargo test --release --all --features cuda,opencl
   Compiling rust-gpu-tools v0.5.0
   Compiling bellperson v0.17.0 (/opt/lotus/gitlab/office_v1.13/bellperson)
error: failed to run custom build command for `bellperson v0.17.0 (/opt/lotus/gitlab/office_v1.13/bellperson)`

Caused by:
  process didn't exit successfully: `/opt/lotus/gitlab/office_v1.13/bellperson/target/release/build/bellperson-ff553e61c49eb35e/build-script-build` (exit code: 101)
  --- stderr
  nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'
  thread 'main' panicked at 'nvcc failed. See the kernel source at /opt/lotus/gitlab/office_v1.13/bellperson/target/release/build/bellperson-1487cf4f8f43ca05/out/aff002a9c65e25912927bcd50f01a0316db06390f6cf242ea369ba6ab96b5a06.cu', build.rs:68:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

```

 ``` 
# export BELLMAN_CUDA_NVCC_ARGS="--fatbin --gpu-architecture=sm_75 --generate-code=arch=compute_75,code=sm_75"
# RUSTFLAGS="-C target-cpu=native" cargo test --release --all --features cuda,opencl
 Compiling bellperson v0.17.0 (/opt/lotus/gitlab/office_v1.13/bellperson)
error: failed to run custom build command for `bellperson v0.17.0 (/opt/lotus/gitlab/office_v1.13/bellperson)`

Caused by:
  process didn't exit successfully: `/opt/lotus/gitlab/office_v1.13/bellperson/target/release/build/bellperson-ff553e61c49eb35e/build-script-build` (exit code: 101)
  --- stderr
  /opt/lotus/gitlab/office_v1.13/bellperson/target/release/build/bellperson-1487cf4f8f43ca05/out/62592a35546d3e7b215cb0b2a0748258c7037e28172d43d8dd7d1c61284137da.cu(1404): error: attribute "__shared__" does not apply here

  1 error detected in the compilation of "/mnt/md0/tmp/tmpxft_00003c39_00000000-6_62592a35546d3e7b215cb0b2a0748258c7037e28172d43d8dd7d1c61284137da.cpp1.ii".
  thread 'main' panicked at 'nvcc failed. See the kernel source at /opt/lotus/gitlab/office_v1.13/bellperson/target/release/build/bellperson-1487cf4f8f43ca05/out/62592a35546d3e7b215cb0b2a0748258c7037e28172d43d8dd7d1c61284137da.cu', build.rs:68:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
     1: std::panicking::begin_panic_fmt
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
     2: build_script_build::main
     3: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
# nvidia-smi
Fri Oct  8 19:52:14 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.67       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
| 30%   40C    P0    57W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:21:00.0 Off |                  N/A |
| 24%   35C    P0    38W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+```

**Comment by dignifiedquire** [comment]
This issue is related to your cuda installation, not the used GPU. Try upgrading cuda to v11.
